# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper8_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6

arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
gripper_controller:
  ros__parameters:
    joints:
      - joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
gripper8_controller:
  ros__parameters:
    joints:
      - joint8
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity